[package]
name = "crosstest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odht = { package = "odht", path = ".." }

[features]
no_simd = ["odht/no_simd"]
