name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Update Stable Rust
      run: rustup update stable
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (no_simd)
      run: cargo test --verbose --features=no_simd
    - name: Build docs
      run: cargo doc --verbose

  benchmarks:
    strategy:
      fail-fast: false
      matrix:
        features: ["nightly", "nightly,no_simd"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly Rust
      run: rustup override set nightly
    - name: Bench
      run: cargo bench --verbose --features=${{ matrix.features }}
